//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tehtava11
{
    using System;
    using System.Collections.Generic;
    
    public partial class PelaajaTiedotKaikki
    {
        public int PID { get; set; }
        public string Nimi { get; set; }
        public string Joukkue { get; set; }
        public Nullable<double> Nr { get; set; }
        public string PP { get; set; }
        public Nullable<int> O { get; set; }
        public Nullable<int> Maalit { get; set; }
        public Nullable<int> Syötöt { get; set; }
        public Nullable<int> Pisteet { get; set; }
        public Nullable<int> R { get; set; }
        public Nullable<int> PlusMinus { get; set; }
        public Nullable<int> YV { get; set; }
        public Nullable<int> AV { get; set; }
        public Nullable<int> VM { get; set; }
        public Nullable<int> L { get; set; }
        public Nullable<int> L_ { get; set; }
        public Nullable<double> Aika { get; set; }
    }
}
